"""Constantes pour l'intégration Sunny."""

DOMAIN = "sunny"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_WINDOWS = "windows"

CONF_WINDOW_NAME = "name"
CONF_WINDOW_ID = "id"
CONF_COVER_ENTITY = "cover_entity"
CONF_ORIENTATION = "orientation"
CONF_WIDTH = "width"
CONF_HEIGHT = "height"
CONF_WALL_THICKNESS = "wall_thickness"
CONF_SCREEN_DISTANCE = "screen_distance"
CONF_SCREEN_HEIGHT = "screen_height"
CONF_TILT_THRESHOLD = "tilt_threshold"
CONF_SLAT_TRANSMISSION = "slat_transmission"
CONF_ALTITUDE = "altitude"
CONF_GROUND_ALTITUDE = "ground_altitude"
CONF_ZONE_ENTITY = "zone_entity"
CONF_STRATEGY = "strategy"
CONF_LATITUDE = "latitude"
CONF_LONGITUDE = "longitude"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_STRATEGY_HIGH = "strategy_high"
CONF_STRATEGY_LOW = "strategy_low"
CONF_TEMP_THRESHOLD = "temp_threshold"
CONF_LIT_THRESHOLD = "lit_threshold"
CONF_TARGET_ILLUMINATION = "target_illumination"

DEFAULT_NAME = "Fenêtre"
DEFAULT_ORIENTATION = 180
DEFAULT_WIDTH = 1.2
DEFAULT_HEIGHT = 1.4
DEFAULT_WALL_THICKNESS = 0.25
DEFAULT_SCREEN_DISTANCE = 0.0
DEFAULT_SCREEN_HEIGHT = 1.0
DEFAULT_TILT_THRESHOLD = 5.0
DEFAULT_SLAT_TRANSMISSION = 5.0
DEFAULT_ALTITUDE = 10
DEFAULT_GROUND_ALTITUDE = 208
DEFAULT_STRATEGY = "block_all"
DEFAULT_REFRESH_INTERVAL = 5
DEFAULT_STRATEGY_HIGH = 50.0
DEFAULT_STRATEGY_LOW = 20.0
DEFAULT_TEMP_THRESHOLD = 28.0
DEFAULT_LIT_THRESHOLD = 20.0
DEFAULT_TARGET_ILLUMINATION = 30.0