"""Constantes pour l'intégration Sunny."""

DOMAIN = "sunny"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_WINDOWS = "windows"

CONF_WINDOW_NAME = "name"
CONF_WINDOW_ID = "id"
CONF_COVER_ENTITY = "cover_entity"
CONF_ORIENTATION = "orientation"
CONF_WIDTH = "width"
CONF_HEIGHT = "height"
CONF_WALL_THICKNESS = "wall_thickness"
CONF_OBSTACLES = "obstacles"

CONF_OBSTACLE_X1 = "ox1"
CONF_OBSTACLE_Y1 = "oy1"
CONF_OBSTACLE_Z1 = "oz1"
CONF_OBSTACLE_X2 = "ox2"
CONF_OBSTACLE_Y2 = "oy2"
CONF_OBSTACLE_Z2 = "oz2"
CONF_TILT_THRESHOLD = "tilt_threshold"
CONF_SLAT_TRANSMISSION = "slat_transmission"
CONF_ALTITUDE = "altitude"
CONF_GROUND_ALTITUDE = "ground_altitude"
CONF_ZONE_ENTITY = "zone_entity"
CONF_STRATEGY = "strategy"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_POSITION_THRESHOLD = "position_threshold"
CONF_STRATEGY_HIGH = "strategy_high"
CONF_STRATEGY_LOW = "strategy_low"
CONF_TEMP_THRESHOLD = "temp_threshold"
CONF_LIT_THRESHOLD = "lit_threshold"
CONF_TARGET_ILLUMINATION = "target_illumination"

DEFAULT_NAME = "Fenêtre"
DEFAULT_ORIENTATION = 180
DEFAULT_WIDTH = 1.2
DEFAULT_HEIGHT = 1.4
DEFAULT_WALL_THICKNESS = 0.25
DEFAULT_OBSTACLES: list = []
DEFAULT_OBSTACLE_X1 = 0.0
DEFAULT_OBSTACLE_Y1 = 0.0
DEFAULT_OBSTACLE_Z1 = 0.0
DEFAULT_OBSTACLE_X2 = 1.0
DEFAULT_OBSTACLE_Y2 = 1.0
DEFAULT_OBSTACLE_Z2 = 1.0
DEFAULT_TILT_THRESHOLD = 5.0
DEFAULT_SLAT_TRANSMISSION = 5.0
DEFAULT_ALTITUDE = 10
DEFAULT_GROUND_ALTITUDE = 208
DEFAULT_STRATEGY = "block_all"
DEFAULT_REFRESH_INTERVAL = 5
DEFAULT_POSITION_THRESHOLD = 3
DEFAULT_STRATEGY_HIGH = 50.0
DEFAULT_STRATEGY_LOW = 20.0
DEFAULT_TEMP_THRESHOLD = 28.0
DEFAULT_LIT_THRESHOLD = 20.0
DEFAULT_TARGET_ILLUMINATION = 30.0